version: '3.7'

services:
  bedlightserver:
    build: .
    ports:
        - "8080:8080"
    environment:
      ESP8266IP: "192.168.178.171"
    secrets:
      - weather_coordinates

secrets:
  weather_coordinates:
    file: coordinates
